[package]
edition = "2021"
name = "otobusum_anlik"
version = "0.1.0"

[dependencies]
anyhow = "1.0.93"
csv = "1.3.1"
dotenvy = "0.15.7"
reqwest = "0.12.9"
serde = { version = "1.0.215", features = ["derive"] }
serde-xml-rs = "0.6.0"
sqlx = { version = "0.8", features = [
    "postgres",
    "runtime-tokio",
    "tls-native-tls",
] }
tokio = { version = "1.41.1", features = ["full"] }
