version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: postgres_iett
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - server 

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379" 

  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    develop:
      watch:
        - path: src
          action: rebuild
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5434/${POSTGRES_DB}
      PORT: $PORT
    networks:
      - server 
    depends_on:
      - postgres


volumes:
  postgres:
  

networks:
  server:


